//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThuVien.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUTRA
    {
        public string MAPHIEUTRA { get; set; }
        public string MATHE { get; set; }
        public string MAPHIEUMUON { get; set; }
    
        public virtual PHIEUMUON PHIEUMUON { get; set; }
        public virtual THETV THETV { get; set; }
    }
}
