//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThuVien.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SACH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SACH()
        {
            this.PHIEUMUONs = new HashSet<PHIEUMUON>();
        }
    
        public string MASACH { get; set; }
        public string TENSACH { get; set; }
        public string TACGIA { get; set; }
        public System.DateTime NGAYXUATBAN { get; set; }
        public string NHAXUATBAN { get; set; }
        public System.DateTime NGAYNHAP { get; set; }
        public string THELOAI { get; set; }
        public decimal TRIGIA { get; set; }
        public int SOLUONG { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUMUON> PHIEUMUONs { get; set; }
    }
}
